### ISSUE TITLE
Unable to link to self hosted cache

### ISSUE THREAD

**Issue by Fractal-Tess** [ducktors/turborepo-remote-cache#146]
## To Reproduce
Host a docker container with simple local storage settings
Try to link & enable cache from client via creating a `.turbo/config.json` with appropriate fields that include `token`, `teamId` and `apiurl`.
Now run `turbo link`, and the on the client you get `error: could not get team information`, while on the server these logs are printed:
```
2023-02-21T18:16:31.570785728Z {"severity":"INFO","level":30,"time":1677003391570,"pid":7,"hostname":"09921250ff30","reqId":"Oe2v3NkCQsO6f_5DaWa91Q-14","res":{"statusCode":404},"responseTime":0.828801155090332,"message":"request completed"}
2023-02-21T18:26:52.569629705Z {"severity":"INFO","level":30,"time":1677004012568,"pid":7,"hostname":"09921250ff30","reqId":"Oe2v3NkCQsO6f_5DaWa91Q-15","req":{"method":"GET","url":"/v2/teams?limit=100","hostname":"myserver.com:36891","remoteAddress":"10.0.0.2","remotePort":52646},"message":"incoming request"}
2023-02-21T18:26:52.569669865Z {"severity":"INFO","level":30,"time":1677004012568,"pid":7,"hostname":"09921250ff30","reqId":"Oe2v3NkCQsO6f_5DaWa91Q-15","message":"Route GET:/v2/teams?limit=100 not found"}
2023-02-21T18:26:52.569674505Z {"severity":"INFO","level":30,"time":1677004012569,"pid":7,"hostname":"09921250ff30","reqId":"Oe2v3NkCQsO6f_5DaWa91Q-15","res":{"statusCode":404},"responseTime":0.45916032791137695,"message":"request completed"}
```

## My environment
Arch 6.1.12-arch1-1
turbo@1.8.1

### Edit:
Just for clarification, running turbo with cli flags like `--team`, `--token` and  `--api` reports that it is using remote cache - 
("Remote caching enabled").

**Comment by Fractal-Tess** [comment]
I''m also getting 
```
2023-02-21T19:31:19.498300890Z {"severity":"INFO","level":30,"time":1677007879498,"pid":7,"hostname":"e7ed71e1d305","reqId":"C83hSXNMSoWAw4bAHmKndA-11","req":{"method":"POST","url":"/v8/artifacts/events?teamId=team_jetblack","hostname":"myserver.com:36891","remoteAddress":"10.0.0.2","remotePort":40928},"message":"incoming request"}
2023-02-21T19:31:19.500350332Z {"severity":"WARNING","level":40,"time":1677007879498,"pid":7,"hostname":"e7ed71e1d305","reqId":"C83hSXNMSoWAw4bAHmKndA-11","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":401,"payload":{"statusCode":401,"error":"Unauthorized","message":"Invalid authorization token"},"headers":{}},"stack":"Error: Invalid authorization token\n    at Object.<anonymous> (/home/app/node/src/plugins/remote-cache/index.ts:41:25)\n    at hookIterator (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/hooks.js:246:10)\n    at next (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/hooks.js:174:16)\n    at hookRunner (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/hooks.js:196:3)\n    at Object.routeHandler [as handler] (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/route.js:469:7)\n    at Router.callHandler (/home/app/node/node_modules/.pnpm/find-my-way@7.4.0/node_modules/find-my-way/index.js:412:14)\n    at Router.lookup (/home/app/node/node_modules/.pnpm/find-my-way@7.4.0/node_modules/find-my-way/index.js:390:17)\n    at Server.preRouting (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/fastify.js:773:14)\n    at Server.emit (node:events:513:28)\n    at Server.emit (node:domain:489:12)","type":"Error","message":"Invalid authorization token"}
2023-02-21T19:31:19.501278732Z {"severity":"INFO","level":30,"time":1677007879501,"pid":7,"hostname":"e7ed71e1d305","reqId":"C83hSXNMSoWAw4bAHmKndA-11","res":{"statusCode":401},"responseTime":2.9591617584228516,"message":"request completed"}

**Comment by fox1t** [comment]
Thanks for reporting this!@
Can I ask you to try with client `turbo@1.7.x`?

**Comment by Fractal-Tess** [comment]
> Thanks for reporting this! Can I ask you to try with client `turbo@1.7.x`?

Hey there and thanks for getting back to me.

I actually tried this yesterday, thinking the API might've updated on how turbo links up to the remote cache server.
I cloned the code and did some logging of the incoming request, and it turns out even though I had a `.turbo/config.json` with properly configured credentials, it was using the config defined in `~/.config/turbo/config.json`. 
I suspect that config was generated when I originally made a connection to the official Cercel remote cache.
I changed the values there and can confirm that the self-hosted remote caching server is properly working without having to use CLI arguments.

The only thing I fail to understand is why it's using the defined config in `~/.config/turbo/config.json` instead of  `.turbo/config.json` at the root of my project.

Anyway, that is all I have for now.

**Comment by Fractal-Tess** [comment]
I think I've figured out how this behaves.

Turborepo doesn't enable cache unless I have a `~/.config/turborepo/config.json` with a `token` field.
I also need a project root level `.turbo/config.json` file for `teamid` and `apiurl`.

**Comment by fox1t** [comment]
This should be added to the documentation. @matteovivona this is the reason we have intermittent remote cache based on the system. The Turborepo team has changed this lately.

**Comment by matteovivona** [comment]
Vercel changed the name of the `teamId` variable to `teamSlug` https://ducktors.github.io/turborepo-remote-cache/custom-remote-caching.html#config-file
