### ISSUE TITLE
Help request - configured with s3, issue in the server log

### ISSUE THREAD

**Issue by imgalli** [ducktors/turborepo-remote-cache#168]
Hi there, we're trying to setup a remote cache using AWS S3 and can see the following error in the log relating to the line of code below. Note using k8s, this image - `ducktors/turborepo-remote-cache:1.14.1`.

```
{"severity":"WARNING","level":40,"time":1684164667390,"pid":7,"hostname":"turborepo-cache-57d6c996db-m8ktx","reqId":"WmEucNymQiefEGn9CLNAYw-0","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"Missing Authorization header"},"headers":{}},"stack":"Error: Missing Authorization header\n    at Object.<anonymous> (/home/app/node/src/plugins/remote-cache/index.ts:56:27)\n    at hookIterator (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/hooks.js:246:10)\n    at next (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/hooks.js:174:16)\n    at hookRunner (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/hooks.js:196:3)\n    at Object.routeHandler [as handler] (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/route.js:469:7)\n    at Router.callHandler (/home/app/node/node_modules/.pnpm/find-my-way@7.6.0/node_modules/find-my-way/index.js:398:14)\n    at Router.lookup (/home/app/node/node_modules/.pnpm/find-my-way@7.6.0/node_modules/find-my-way/index.js:376:17)\n    at Server.preRouting (/home/app/node/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/fastify.js:773:14)\n    at Server.emit (node:events:513:28)\n    at Server.emit (node:domain:489:12)","type":"Error","message":"Missing Authorization header"}
```

https://github.com/ducktors/turborepo-remote-cache/blob/main/src/plugins/remote-cache/index.ts#L56

The following env vars are set, key and secret via `~/.aws`.
```
STORAGE_PROVIDER - s3
STORAGE_PATH - something
AWS_REGION - eu-west-2
S3_ENDPOINT - https://XXX.s3.eu-west-2.amazonaws.com
```

This is a result of trying to run a command against this server, local command being 
```
turbo run ci:lint -vvv --remote-only
```

with `.turbo/config.json` of

```
{
  "teamId": "team_myteam",
  "apiUrl": "XXXXX",
  "token": "XXXXX"
}
```

**Comment by fox1t** [comment]
Hey. The project config file doesn’t support passing the token. This is a turbo limitation. You should use one of the 3 methods described here https://ducktors.github.io/turborepo-remote-cache/custom-remote-caching#config-file

**Comment by imgalli** [comment]
Hey @fox1t , thanks for the reply!

We tried using only ENV vars listed here and had the same result - https://ducktors.github.io/turborepo-remote-cache/custom-remote-caching#local-environment-variables

**Comment by lperrious** [comment]
Hey @fox1t, is there any solution for this issue please ?

**Comment by lperrious** [comment]
I had some time to work on it again. It turns out that the `TURBO_TOKEN` was causing problems due to a special character.
It works perfectly now. 
Thanks for your work !
