### ISSUE TITLE
Where can I found my S3_ENDPOINT in docker setup? have error: Artifact not found 

### ISSUE THREAD

**Issue by zigang93** [ducktors/turborepo-remote-cache#40]
Hi, I am not sure which S3_ENDPOINT you are refer to ? where can I find it at aws? 

aws bucket name: turbo-repo

my .env config

```bash
NODE_ENV=production
PORT=3000
TURBO_TOKEN=yourToken
LOG_LEVEL=info
STORAGE_PROVIDER=s3
STORAGE_PATH=turbo-repo
AWS_ACCESS_KEY_ID=<aws secret  id>
AWS_SECRET_ACCESS_KEY=<aws secret key>
AWS_REGION=ap-southeast-1
S3_ENDPOINT=http://turbo-repo.s3.ap-southeast-1.amazonaws.com
```

I get some error in my docker logs.. not sure what Artifact means..
```bash
{"severity":"WARNING","level":40,"time":1662821516456,"pid":7,"hostname":"7467bd81768e","reqId":"oEKrAxmVR0K3hrHPnmpmcA-1","data":{},"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"Artifact not found"},"headers":{}},"stack":"/home/app/node/src/plugins/remote-cache/routes/get-artifact.ts:29\n      throw notFound(`Artifact not found`, err)\n                    ^\n\nError: Artifact not found\n    at Object.handler (/home/app/node/src/plugins/remote-cache/routes/get-artifact.ts:29:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","type":"Error","message":"Artifact not found"}
{"severity":"INFO","level":30,"time":1662821516458,"pid":7,"hostname":"7467bd81768e","reqId":"oEKrAxmVR0K3hrHPnmpmcA-1","res":{"statusCode":404},"responseTime":53.324764251708984,"message":"request completed"}
{"severity":"INFO","level":30,"time":1662821516696,"pid":7,"hostname":"7467bd81768e","reqId":"oEKrAxmVR0K3hrHPnmpmcA-2","req":{"method":"POST","url":"/v8/artifacts/events?teamId=team_pingspace_wcs","hostname":"turborepo-cache.pingspace.co","remoteAddress":"161.142.173.156","remotePort":37378},"message":"incoming request"}
{"severity":"INFO","level":30,"time":1662821516702,"pid":7,"hostname":"7467bd81768e","reqId":"oEKrAxmVR0K3hrHPnmpmcA-2","res":{"statusCode":200},"responseTime":4.817142486572266,"message":"request completed"}
```

I am pretty sure that my aws access id and secret is able to upload .env file to bucket
```bash
aws s3api put-object --bucket turbo-repo --key .env --body .env
```

**Comment by fox1t** [comment]
If you use `AWS_REGION`, you can remove `S3_ENDPOINT`. Only one of two is mandatory. Let me know if it works. 

FYI, the warning (404  error) you see is standard since the server couldn't find the artifact. An artifact is a remotely cached version of your local turborepo command execution.

**Comment by zigang93** [comment]
> If you use `AWS_REGION`, you can remove `S3_ENDPOINT`. Only one of two is mandatory. Let me know if it works.
> 
> FYI, the warning (404 error) you see is standard since the server couldn't find the artifact. An artifact is a remotely cached version of your local turborepo command execution.

I removed `S3_ENDPOINT` at .env file..
but it still show `Artifact not found`.. I still don't understand `An artifact is a remotely cached version of your local turborepo command execution.` mean? I checked my s3 bucket.. still empty

**Comment by zigang93** [comment]
my latest logs from docker
```bash
{"severity":"INFO","level":30,"time":1663637003773,"pid":7,"hostname":"c2fb30aceb5c","message":"Server listening at http://0.0.0.0:3000"}
{"severity":"INFO","level":30,"time":1663637021482,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-0","req":{"method":"POST","url":"/v8/artifacts/events?slug=team_pingspace_wcs&teamId=team_pingspace_wcs","hostname":"turborepo-cache.pingspace.co","remoteAddress":"118.101.192.73","remotePort":49408},"message":"incoming request"}
{"severity":"INFO","level":30,"time":1663637021501,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-0","res":{"statusCode":200},"responseTime":16.02419662475586,"message":"request completed"}
{"severity":"INFO","level":30,"time":1663637021503,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-1","req":{"method":"GET","url":"/v8/artifacts/70476cc6f96f028a?slug=team_pingspace_wcs&teamId=team_pingspace_wcs","hostname":"turborepo-cache.pingspace.co","remoteAddress":"118.101.192.73","remotePort":49410},"message":"incoming request"}
{"severity":"INFO","level":30,"time":1663637021551,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-2","req":{"method":"GET","url":"/v8/artifacts/21fb2254ce4d2f9c?slug=team_pingspace_wcs&teamId=team_pingspace_wcs","hostname":"turborepo-cache.pingspace.co","remoteAddress":"118.101.192.73","remotePort":49414},"message":"incoming request"}
{"severity":"WARNING","level":40,"time":1663637021609,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-1","data":{},"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"Artifact not found"},"headers":{}},"stack":"/home/app/node/src/plugins/remote-cache/routes/get-artifact.ts:29\n      throw notFound(`Artifact not found`, err)\n                    ^\n\nError: Artifact not found\n    at Object.handler (/home/app/node/src/plugins/remote-cache/routes/get-artifact.ts:29:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","type":"Error","message":"Artifact not found"}
{"severity":"INFO","level":30,"time":1663637021615,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-1","res":{"statusCode":404},"responseTime":111.70306777954102,"message":"request completed"}
{"severity":"WARNING","level":40,"time":1663637021618,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-2","data":{},"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"Artifact not found"},"headers":{}},"stack":"/home/app/node/src/plugins/remote-cache/routes/get-artifact.ts:29\n      throw notFound(`Artifact not found`, err)\n                    ^\n\nError: Artifact not found\n    at Object.handler (/home/app/node/src/plugins/remote-cache/routes/get-artifact.ts:29:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","type":"Error","message":"Artifact not found"}
{"severity":"INFO","level":30,"time":1663637021620,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-2","res":{"statusCode":404},"responseTime":65.06990432739258,"message":"request completed"}
{"severity":"INFO","level":30,"time":1663637022204,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-3","req":{"method":"POST","url":"/v8/artifacts/events?slug=team_pingspace_wcs&teamId=team_pingspace_wcs","hostname":"turborepo-cache.pingspace.co","remoteAddress":"118.101.192.73","remotePort":49422},"message":"incoming request"}
{"severity":"INFO","level":30,"time":1663637022206,"pid":7,"hostname":"c2fb30aceb5c","reqId":"teYalIleSSyeUY1zjbBq6A-3","res":{"statusCode":200},"responseTime":2.208415985107422,"message":"request completed"}
^C
```

**Comment by zigang93** [comment]
Update: 
I finally found out the problem.. I am using `nginx` to do the reverse proxy to https domain.. but turn out it can't work.. I am not sure why.. I am using pure ip address .. then it work well..
