### ISSUE TITLE
FastifyError [Error]: logger options only accepts a configuration object.

### ISSUE THREAD

**Issue by kaiburjack** [ducktors/turborepo-remote-cache#479]
## 🐛 Bug Report

After upgrading from 2.2.5 to 2.2.6, the service crashes with the error message:
```
/home/app/node/node_modules/.pnpm/@fastify+error@4.0.0/node_modules/@fastify/error/index.js:18
      return new FastifyError(...args)
             ^
FastifyError [Error]: logger options only accepts a configuration object.
    at FastifyError (/home/app/node/node_modules/.pnpm/@fastify+error@4.0.0/node_modules/@fastify/error/index.js:18:14)
    at createLogger (/home/app/node/node_modules/.pnpm/fastify@5.1.0/node_modules/fastify/lib/logger-factory.js:100:11)
    at fastify (/home/app/node/node_modules/.pnpm/fastify@5.1.0/node_modules/fastify/fastify.js:139:33)
    at createApp (/home/app/node/src/app.ts:11:15)
    at <anonymous> (/home/app/node/src/index.ts:6:13)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  code: 'FST_ERR_LOG_INVALID_LOGGER_CONFIG',
  statusCode: 500
}

Node.js v20.13.1
```

We are using the ducktors/turborepo-remote-cache:2.2.6 Docker Image.

## To Reproduce

- start the turbo repo cache using the ducktors/turborepo-remote-cache:2.2.6 Docker image e.g. via:
```bash
docker run -e TURBO_TOKEN=... ducktors/turborepo-remote-cache:2.2.6
```

## Expected behavior

The service starts successfully as expected, just like in version 2.2.5.

## Your Environment

- _OS_: Linux
- _Cloud Vendor_: GCP/GKE
- _Turbo Version_: 2.2.6

**Comment by mattref** [comment]
This appears to be caused by the [Fastify version bump](#474), which didn't account for [Fastify v5's "New logger constructor signature"](https://fastify.dev/docs/v5.1.x/Guides/Migration-Guide-V5/#new-logger-constructor-signature), which is mentioned in the migration guide.

**Comment by kaiburjack** [comment]
Indeed, it works! Thanks for the very quick fix!
